#name: bloggios-service-registry load
#
#on:
#  workflow_run:
#    workflows: ["bloggios-service-registry"]
#    types:
#      - completed
#
#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          server-id: github
#          settings-path: ${{ github.workspace }}
#      - uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
#
#      - name: Stopping Container
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.V4_HOST }}
#          username: ${{ secrets.V4_USERNAME }}
#          key: ${{ secrets.V4_VPS_PRIVATE_KEY }}
#          port: 22
#          script: |
#            cd /root/bloggios-deployment-docker-files
#            git stash
#            git pull origin main
#            set +e
#            docker-compose -f docker-compose-load.yml stop bloggios-service-registry
#            docker rmi bloggios-service-registry:1.0
#            set -e
#
#      - name: Copying Logback
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.V4_HOST }}
#          username: ${{ secrets.V4_USERNAME }}
#          key: ${{ secrets.V4_VPS_PRIVATE_KEY }}
#          port: 22
#          script: |
#            rm /root/microservices/bloggios-service-registry/src/main/resources/registry-logback.xml
#            cp /root/secrets/logback/registry-logback.xml /root/microservices/bloggios-service-registry/src/main/resources
#
#      - name: Generating Docker Image for Bloggios
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.V4_HOST }}
#          username: ${{ secrets.V4_USERNAME }}
#          key: ${{ secrets.V4_VPS_PRIVATE_KEY }}
#          port: 22
#          script: |
#            cd /root/microservices/bloggios-service-registry
#            git stash
#            git pull origin main
#            chmod +x mvnw
#            ./mvnw clean package
#
#      - name: Deploy Docker Image
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.V4_HOST }}
#          username: ${{ secrets.V4_USERNAME }}
#          key: ${{ secrets.V4_VPS_PRIVATE_KEY }}
#          port: 22
#          script: |
#            cd /root/bloggios-deployment-docker-files
#            docker-compose -f docker-compose-load.yml up -d bloggios-service-registry
#
#      - name: Removing Targets
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.V4_HOST }}
#          username: ${{ secrets.V4_USERNAME }}
#          key: ${{ secrets.V4_VPS_PRIVATE_KEY }}
#          port: 22
#          script: |
#            cd /root/microservices/bloggios-service-registry
#            rm target -r